SERVER_ID=s1
ISUCON_DB_USER=isucon
ISUCON_DB_PASSWORD=isucon
ISUCON_DB_HOST=52.194.37.96
ISUCON_DB_PORT=3306
ISUCON_DB_NAME=isucon
SERVER_APP_PORT=8080
PERL5LIB=/home/isucon/webapp/perl/local/lib/perl5